interface FrontmatterBlock {
  body: string;
  end: number;
  start: number;
}

interface FrontmatterSection {
  key: string;
  text: string;
}

const FRONTMATTER_BLOCK_RE = /^(---\r?\n)([\s\S]*?)(\r?\n---(?:\r?\n|$))/;
const FRONTMATTER_KEY_RE = /^([A-Za-z][A-Za-z0-9_-]*):[^\r\n]*(?:\r?\n|$)/gm;

function getFrontmatterBlock(content: string): FrontmatterBlock | null {
  const match = FRONTMATTER_BLOCK_RE.exec(content);
  if (!match) return null;

  const start = match[1].length;
  return {
    body: match[2],
    start,
    end: start + match[2].length,
  };
}

function getTopLevelSections(frontmatter: string): FrontmatterSection[] {
  const matches = Array.from(frontmatter.matchAll(FRONTMATTER_KEY_RE));
  return matches.map((match, index) => ({
    key: match[1],
    text: frontmatter.slice(
      match.index,
      index + 1 < matches.length ? matches[index + 1].index : frontmatter.length,
    ),
  }));
}

/**
 * Update only the top-level fields generated by the current note template.
 * Other frontmatter properties and everything below the frontmatter stay put.
 */
export function refreshTemplateFrontmatter(
  existingContent: string,
  refreshedTemplateContent: string,
): string | null {
  const existingBlock = getFrontmatterBlock(existingContent);
  const refreshedBlock = getFrontmatterBlock(refreshedTemplateContent);
  if (!existingBlock || !refreshedBlock) return null;

  const existingSections = getTopLevelSections(existingBlock.body);
  const refreshedSections = getTopLevelSections(refreshedBlock.body);
  const refreshedByKey = new Map(
    refreshedSections.map((section) => [section.key, section.text]),
  );

  let updatedFrontmatter = existingBlock.body;
  for (const section of [...existingSections].reverse()) {
    const replacement = refreshedByKey.get(section.key);
    if (!replacement) continue;

    const index = updatedFrontmatter.lastIndexOf(section.text);
    updatedFrontmatter =
      updatedFrontmatter.slice(0, index) +
      replacement +
      updatedFrontmatter.slice(index + section.text.length);
  }

  const existingKeys = new Set(existingSections.map((section) => section.key));
  const missingSections = refreshedSections.filter(
    (section) => !existingKeys.has(section.key),
  );
  if (missingSections.length > 0) {
    const lineBreak = updatedFrontmatter.includes('\r\n') ? '\r\n' : '\n';
    if (updatedFrontmatter && !updatedFrontmatter.endsWith(lineBreak)) {
      updatedFrontmatter += lineBreak;
    }
    updatedFrontmatter += missingSections.map((section) => section.text).join('');
  }

  return (
    existingContent.slice(0, existingBlock.start) +
    updatedFrontmatter +
    existingContent.slice(existingBlock.end)
  );
}
